Traceback (most recent call last):
  File "/home/ryan/python/Python_automation/10_调试/10.2_取得反向追踪字符串.py", line 4, in <module>
    raise Exception("This is a test error")
Exception: This is a test error
